apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.idm.serviceName}}
spec:
  selector:
    app: {{ .Values.idm.name }}
  ports:
    - port: {{ .Values.idm.port}}
      targetPort: {{ .Values.vo.targetPort}}
  type: {{ .Values.service.type}}
