apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: {{ .Values.spec.port }}
      targetPort: 8080

  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }}

